### ISSUE TITLE
🚀 Docker Compose file with explanation

### ISSUE THREAD

**Issue by DaanSelen** [eritislami/evobot#1639]
**Is your feature request related to a problem? Please describe.**
Is there a Docker-compose.yaml file?

**Describe the solution you'd like**
A working docker compose file, with perhaps a precompiled Docker image.

**Describe alternatives you've considered**
Compiling it myself every time once there is an update.

**Comment by j0hnVu** [comment]
```
name: evobot-1
services:
    evobot:
        environment:
            - TOKEN="YOUR_TOKEN"
        image: eritislami/evobot
        restart: always
```

I've been using this for a while. Maybe this is what you are looking for?
